import { Review } from './types';

export const REVIEWS: Review[] = [
  {
    id: '1',
    title: '에스티로더 더블웨어 파운데이션 6개월 사용 후기',
    content: '지성 피부라 파운데이션 지속력에 항상 불만이었는데, 이건 진짜 다르네요. 오후 5시까지도 무너짐 없이 지속됩니다. 커버력도 충분하고 촉촉한 느낌도 오래 가요.',
    category: 'BEAUTY',
    author: 'minji_k',
    rating: 4.8,
    viewCount: 12400,
    helpfulCount: 890,
    tags: ['파운데이션', '지속력', '지성피부', '에스티로더'],
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    personalColor: 'WINTER_COOL',
    createdAt: '2024-03-15',
  },
  {
    id: '2',
    title: '봄 웜톤 추천 블러셔 TOP3 비교 리뷰',
    content: '봄 웜톤에 어울리는 블러셔를 3가지 비교해봤습니다. 피치, 코랄, 살구 컬러 각각의 발색과 지속력을 꼼꼼히 테스트했어요.',
    category: 'BEAUTY',
    author: 'sunny_tone',
    rating: 4.6,
    viewCount: 8900,
    helpfulCount: 720,
    tags: ['블러셔', '봄웜톤', '비교리뷰', '발색'],
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=800&auto=format&fit=crop',
    personalColor: 'SPRING_WARM',
    createdAt: '2024-03-10',
  },
  {
    id: '3',
    title: '여름 쿨톤 립 메이크업 완성하기 - 베리 계열 추천',
    content: '쿨톤에게 베리 컬러 립은 필수입니다. 5가지 제품 비교해봤어요. 발색, 보습력, 지속력 모두 체크했습니다.',
    category: 'BEAUTY',
    author: 'cool_summer',
    rating: 4.9,
    viewCount: 15200,
    helpfulCount: 1100,
    tags: ['립스틱', '쿨톤', '베리립', '여름'],
    image: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4877?q=80&w=800&auto=format&fit=crop',
    personalColor: 'SUMMER_COOL',
    createdAt: '2024-03-08',
  },
  {
    id: '4',
    title: '가을 웜톤 아이섀도우 팔레트 솔직 후기',
    content: '어스톤 팔레트가 가을 웜톤에게 잘 어울린다고 하는데 직접 써보니 정말 그렇더라고요. 브라운, 테라코타, 카키 컬러가 모두 피부와 자연스럽게 어우러졌어요.',
    category: 'BEAUTY',
    author: 'autumn_glow',
    rating: 4.7,
    viewCount: 7600,
    helpfulCount: 540,
    tags: ['아이섀도우', '가을웜톤', '어스톤', '팔레트'],
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=800&auto=format&fit=crop',
    personalColor: 'AUTUMN_WARM',
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    title: '강남 피부과 레이저 토닝 3회 후기 - 가격 포함',
    content: '기미 때문에 레이저 토닝 시작했는데 3회 받고 확실히 밝아진 것 같아요. 가격 정보, 통증 정도, 회복 기간까지 솔직하게 공유합니다.',
    category: 'PROCEDURE',
    author: 'skin_diary',
    rating: 4.5,
    viewCount: 21000,
    helpfulCount: 1560,
    tags: ['레이저토닝', '피부과', '기미', '강남'],
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-03-12',
  },
  {
    id: '6',
    title: '보톡스 처음 맞아봤습니다 - 이마 + 눈가 시술 후기',
    content: '30대 초반에 처음으로 보톡스를 맞아봤어요. 시술 과정, 통증, 자연스러운 정도, 지속 기간에 대해 솔직하게 이야기해볼게요.',
    category: 'PROCEDURE',
    author: 'botox_first',
    rating: 4.3,
    viewCount: 18500,
    helpfulCount: 1200,
    tags: ['보톡스', '이마보톡스', '눈가주름', '시술후기'],
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-03-03',
  },
  {
    id: '7',
    title: '2024 봄 시즌 린넨 소재 완벽 분석 후기',
    content: '실제 원단감부터 체형별 핏까지 꼼꼼하게 비교 분석했습니다. 5가지 브랜드의 린넨 아이템을 직접 입어보고 비교했어요.',
    category: 'FASHION',
    author: 'linen_lover',
    rating: 4.7,
    viewCount: 9800,
    helpfulCount: 670,
    tags: ['린넨', '봄패션', '소재비교', '2024트렌드'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-03-14',
  },
  {
    id: '8',
    title: '직장인 데일리룩 쇼핑몰 TOP5 솔직 비교',
    content: '출근룩 쇼핑몰 5곳을 3개월 동안 직접 이용해봤습니다. 가격대, 사이즈 정확도, 품질, AS까지 모두 비교해드릴게요.',
    category: 'FASHION',
    author: 'office_style',
    rating: 4.4,
    viewCount: 13400,
    helpfulCount: 980,
    tags: ['직장인룩', '쇼핑몰추천', '데일리룩', '가성비'],
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-03-01',
  },
  {
    id: '9',
    title: '필러 시술 6개월 경과 후기 - 자연스러운가요?',
    content: '애플 필러 맞은 지 6개월이 지났어요. 처음부터 지금까지 변화 과정, 자연스러운 정도, 유지 기간을 솔직하게 공유해드립니다.',
    category: 'PROCEDURE',
    author: 'filler_diary',
    rating: 4.1,
    viewCount: 16200,
    helpfulCount: 1030,
    tags: ['필러', '애플필러', '시술후기', '6개월경과'],
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-02-28',
  },
  {
    id: '10',
    title: '겨울 쿨톤을 위한 완벽한 누드 메이크업 가이드',
    content: '쿨톤 피부에 어울리는 누드 메이크업, 베이지가 아니라 핑크 베이스로 잡아야 해요. 단계별로 제품 추천과 함께 설명해드릴게요.',
    category: 'BEAUTY',
    author: 'winter_cool',
    rating: 4.8,
    viewCount: 11300,
    helpfulCount: 870,
    tags: ['쿨톤메이크업', '누드메이크업', '겨울쿨톤', '메이크업가이드'],
    image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?q=80&w=800&auto=format&fit=crop',
    personalColor: 'WINTER_COOL',
    createdAt: '2024-02-25',
  },
  {
    id: '11',
    title: '무신사 vs 29CM 쇼핑몰 비교 리뷰',
    content: '두 쇼핑몰에서 각각 50만원씩 써봤습니다. 상품 다양성, 배송 속도, 반품 편의성, 가격 경쟁력을 꼼꼼히 비교해봤어요.',
    category: 'FASHION',
    author: 'fashion_lab',
    rating: 4.2,
    viewCount: 22000,
    helpfulCount: 1450,
    tags: ['무신사', '29cm', '쇼핑몰비교', '패션앱'],
    image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-02-20',
  },
  {
    id: '12',
    title: '여드름 흉터 레이저 치료 1년 기록',
    content: '여드름 흉터 때문에 고민하다가 레이저 치료를 시작했습니다. 프락셀부터 CO2 레이저까지 1년 동안의 치료 기록을 공유해드려요.',
    category: 'PROCEDURE',
    author: 'acne_free',
    rating: 4.6,
    viewCount: 19800,
    helpfulCount: 1340,
    tags: ['여드름흉터', '레이저치료', '프락셀', '피부과'],
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=800&auto=format&fit=crop',
    createdAt: '2024-02-18',
  },
];
